namespace: brianreumere
name: util
version: false
readme: README.md
authors:
  - Brian Reumere <brian@mutualaid.info>
description: Ansible collection for utility functions
license:
  - ISC
repository: https://github.com/brianreumere/brianreumere.util
