---
dependencies: []
galaxy_info:
  role_name: install_from_url
  description: Install something from a URL
  min_ansible_version: '2.12'
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
    - name: OpenBSD
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
