---
dependencies: []
galaxy_info:
  namespace: brianreumere
  role_name: install_from_url
  author: Brian Reumere
  description: Install something from a URL
  license: ISC
  min_ansible_version: '2.12'
  github_branch: main
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: OpenBSD
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
